config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get "home/about" => "home#about"
  get "/users" => "users#index"
  post "/books/create" => "books#create"

  resources :users

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true,
                   length: { minimum: 2, maximum: 20 }

  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # deviseコントローラーにストロングパラメータを追加する
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
  root_path
  end

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    # アカウント編集の時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

Refile.secret_key = '690eb9bd619be89aaa9bca9171b0fa8e391c10850f796583ef5e49fd66e939432d682a7795153bad9e1f7d205919b9c78db27731c787030196396b1af97495bf'

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def ensure_correct_user
     @book = Book.find(params[:id])
     if @book.user_id != current_user.id
     redirect_to books_path
     end
  end


	def show
		@book = Book.find(params[:id])
        @newbook = Book.new
        @user = @book.user
	end

	def index
		@books = Book.all
		@newbook = Book.new
		@user = current_user
		@book = Book.new
	end

	def new
		@newbook = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
        if @book.save
        flash[:notice] = "You have created book successfully"
        redirect_to book_path(@book.id)
        else
        @books= Book.all
        @user = current_user
        @newbook = Book.new
        render :index
        end
	end

	def edit
		@book= Book.find(params[:id])
	end

	def update
		@book = Book.find_by(id: params[:id])
	  	if @book.update(book_params)
	  	#保存できた場合
	    redirect_to book_path(@book)
	    flash[:notice] = "Book was successfully updated."
	    else
	    #保存できなかった場合
	    render :edit
	    end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

    private

	def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # ログインユーザーとユーザー編集されるユーザーが異なる場合弾く
  before_action :ensure_correct_user, {only:[:edit, :update]}

  def ensure_correct_user
     @user = User.find(params[:id])
     if @user.id != current_user.id
     redirect_to user_path(current_user.id)
     end
  end

  def index
  	@users = User.all
    @newbook = Book.new
    @user = current_user
  end
  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @newbook = Book.new
  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	if @user.save
  		redirect_to user_path(@user.id)
      flash[:notice] = "Profile was successfully updated."
  	else
  		render :edit
  	end
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%if @book.errors.any? %>
<h3><%="#{@book.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
<%end%>

<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<!-- form_for部分 -->
<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Update Book' %>
<% end %>

<td><%= link_to "Show", book_path(@book.id) %><td>
|
<a href = "/books">Back</a>

app/views/books/index.html.erb
<%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>

<%if @book.errors.any? %>
<h3><%="#{@book.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
<%end%>

<% @book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<div class="col-xs-9">
	<h2>Books</h2>
	  <table class="table" >
	    <thead>
	    	<tr>
	    	  <th></th>
	    	  <th>Title</th>
	    	  <th>Opinion</th>
	    	</tr>
	    </thead>
    <% @books.each do |book| %>
	    <tbody>
	    	<tr>
	    	  <td>
                <%= link_to user_path(book.user) do %>
		    	  	<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
	    	  	<% end %>
	    	  	</td>
	          <td><%= link_to book.title, book_path(book.id) %></td>
	    	  <td><%= book.body%></td>
	    	</tr>
	    </tbody>
	<% end %>
	    </table>
</div>


app/views/books/new.html.erb
<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@book, url:"/books/create") do |f| %>
    <% @book.errors.full_messages.each do |message| %>
              <%= message %>
    <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>

<div class="col-xs-9">
	<h2>Book detail</h2>
	    <table class="table">
	    	<tbody>
	    	  <tr>
	    	  	  <td>
				    <%= link_to user_path(@user.id) do %>
				    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
				    <br><%= "#{@user.name}" %>
				    <%end%>
				  </td>
				  <td>
					<p class = "book-title"><%= link_to "#{@book.title}",book_path(@book.id) %></p>
				  </td>
				  <td>
					<p class = "book-body"><%= @book.body %></p>
                  </td>
				  <% if @book.user_id == current_user.id %>
				  <td>
				  	<%= link_to edit_book_path do %>
				  	<button type="button" class="btn btn-info">Edit</button>
				  	<%end%>
				  </td>
				  <td>
					<%= link_to book_path, method: :delete, data: { confirm: '削除しますか？' } do %>
					<button type="button" class="btn btn-danger">Destroy</button>
				  	<%end%>
				  </td>
					<% end %>
			  </tr>
			</tbody>
       </table>
</div>

app/views/home/about.html.erb
<h1>welcome to <strong>Bookers</strong>  !!</h1>

app/views/home/index.html.erb
<div class = "row">
	<div class="col-xs-offset-3 col-xs-6">

		<h1>welcome to
			<strong>
				<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers
			</strong>  !!
		</h1>


		<p>In
		<span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers<br>
		you can share and exchange your opinions , inpressions , and emotions<br>
		about varioius books!</p>

		<div class = "btn-wrapper">
			<div class ="row">
				<%=link_to new_user_session_path do %>
				<button type="button" class="btn btn-info col-xs-offset-1 col-xs-10 sign_in">Log in</button>
				<%end%>

				<%=link_to new_user_registration_path do %>
				<button type="button" class="btn btn-success col-xs-offset-1 col-xs-10">Sign up</button>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<div class ="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg",size:'100x100' %>

    <table class="table">
		<tbody>
			<tr>
			<th>name</th>
			<th><%= user.name %></th>
		   </tr>
			<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		   </tr>
        </tbody>
    </table>
    <div class="row">
	<%= link_to "", edit_user_path(current_user.id), :class => "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>

	<h2>New book</h2>
	<!-- form_for部分 -->
	<%= form_for newbook do |f|%>
	    <% newbook.errors.full_messages.each do |message| %>
	              <%= message %>
	    <% end %>
	    <h4>Title</h4>
	    <%= f.text_field :title %>

	    <h4>Opinion</h4>
	    <%= f.text_area :body %>

        <div class ="row">
	    <%= f.submit 'Create Book', :class => "btn btn-primary col-xs-12" %>
        </div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <span class="navbar-brand">Bookers</span>
        </div>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user.id),:class => "glyphicon glyphicon-home" %></li>
          <li><%= link_to ' Users', "/users", :class => "glyphicon glyphicon-user" %></li>
          <li><%= link_to ' Books', books_path, :class => "glyphicon glyphicon-book" %></li>
          <li><%= link_to " Logout", destroy_user_session_path, method: :delete, :class => "glyphicon glyphicon-log-out" %></li>
      <% else %>
          <li><%= link_to " Home", root_path, :class => "glyphicon glyphicon-home" %></li>
          <li><%= link_to " About", home_about_path, :class =>"glyphicon glyphicon-link" %></li>
          <li><%= link_to " Sign up", new_user_registration_path, :class => "glyphicon glyphicon-edit" %></li>
          <li><%= link_to " Log in", new_user_session_path, :class => "glyphicon glyphicon-log-in" %></li>
      <% end %>
      </ul>
    </div>
    </nav>
  </header>

<div class="container">
  <div class ="row">
  <%= notice %>
  <%= alert %>
    <%= yield %>
  </div>
</div>


    <footer>
      <div class ="container">
        <div class ="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>

    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>

<%if @user.errors.any? %>
<h3><%="#{@user.errors.full_messages.count} errors prohibited this obj being saved:" %></h3>
<%end%>

<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>

<%= form_for (@user) do |f| %>
<p>Name</p>
<%= f.text_field :name %>
<p>Image</p>
<%= f.attachment_field :profile_image %>
<p>Introduction</p>
<%= f.text_area :introduction %>
<%= f.submit "Update Profile" %>
<%end%>

app/views/users/index.html.erb
<%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>

<div class= "col-xs-9">
	<h1>Users</h1>
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
		        <th></th>
		    </tr>
		</thead>
		<% @users.each do |user| %>
		<tbody>
	        <tr>
				<td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:'30x30' %></td>
				<td><%= user.name %></td>
				<td><%= link_to("show","/users/#{user.id}") %></td>
		    </tr>
	    </tbody>
		<%end%>
	</table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render partial: 'layouts/sidebar', locals:{ user: @user, newbook: @newbook } %>


<div class="col-xs-9">
	<h2>Books</h2>
		<table class="table" >
		<thead>
			<tr>
				<th></th>
			  <th>Title</th>
			  <th>Opinion</th>
			</tr>
		</thead>
		    <tr>
		<% @books.each do |book| %>
		<tbody>
			  <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'50x50' %>
			  	<!--%= link_to ,book.user, user_path(user.id) %-->
			  </td>
		      <td><%= link_to book.title, book_path(book.id) %></td>
			  <td><%= book.body%></td>
		</tbody>
			</tr>
		<% end %>
		</table>